before_install:
  - sudo apt-get update
install:
  - sudo apt-get install sqlite3
  - curl https://static.rust-lang.org/rustup.sh | sudo bash
notifications:
  email: false
script:
  - /usr/local/bin/cargo build --verbose
  - /usr/local/bin/cargo test --verbose
